Upgrade floneumite's octocrab to 0.44.0 (#372)
The current version depends on an incompatible version of `pin-project` that prevents `floneum` from compiling:
```
error: failed to select a version for `pin-project`.
    ... required by package `voice_activity_detector v0.2.0`
    ... which satisfies dependency `voice_activity_detector = "^0.2.0"` of package `kalosm-sound v0.4.0 (/Users/alexaraujo/dev/floneum/interfaces/kalosm-sound)`
    ... which satisfies path dependency `kalosm-sound` (locked to 0.4.0) of package `kalosm v0.4.0 (/Users/alexaraujo/dev/floneum/interfaces/kalosm)`
    ... which satisfies path dependency `kalosm` (locked to 0.4.0) of package `floneum_plugin v0.1.0 (/Users/alexaraujo/dev/floneum/floneum/plugin)`
    ... which satisfies path dependency `floneum_plugin` (locked to 0.1.0) of package `floneum v0.1.0 (/Users/alexaraujo/dev/floneum/floneum/floneum)`
versions that meet the requirements `^1.1.10` are: 1.1.10

all possible versions conflict with previously selected packages.

  previously selected package `pin-project v1.1.9`
    ... which satisfies dependency `pin-project = "^1.0.12"` (locked to 1.1.9) of package `octocrab v0.30.1`
    ... which satisfies dependency `octocrab = "^0.30.1"` (locked to 0.30.1) of package `floneumite v0.1.0 (/Users/alexaraujo/dev/floneum/floneum/floneumite)`
    ... which satisfies path dependency `floneumite` (locked to 0.1.0) of package `floneum v0.1.0 (/Users/alexaraujo/dev/floneum/floneum/floneum)`
```